#!/usr/bin/env python3
"""
panel_summary.py -- collect the Table 5 sensitivity panel (panel.sh) into a report.

Reads julia/spatial_model/calibration/runs/panel/<case>/{theta.toml,report.txt} for every case
of panel_cases.tsv, plus the baseline estimate, and writes
data/spatial/estimates/sensitivity_panel.md: the estimates, the criterion and the
moments that move, one row per case. Run from the repository root:

    python3 julia/spatial_model/calibration/slurm/panel_summary.py [--baseline julia/spatial_model/calibration/runs/polish-noincome]
"""
import argparse
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
PANEL = ROOT / "julia/spatial_model/calibration/runs/panel"
CASES = ROOT / "julia/spatial_model/calibration/slurm/panel_cases.tsv"
OUT = ROOT / "data/spatial/estimates/sensitivity_panel.md"

NAMES = ["logκ̃", "δκ", "ΔB", "β", "λ", "r_m", "ωf", "γ"]
# moments reported from the moment table (model value, then the standardized residual)
MOMENTS = ["teacher_p9010", "gap_salary", "gap_pupils", "gap_teachers_pp", "move_rate", "gap_income"]


def read_run(d: Path):
    """ϑ, criterion and moment-table rows of one spatial_diagnose.jl --out directory."""
    toml = d / "theta.toml"
    rep = d / "report.txt"
    if not (toml.exists() and rep.exists()):
        return None
    t = tomllib.loads(toml.read_text())
    text = rep.read_text()
    rows = {}
    table = text.split("criterion over", 1)[0]      # the moment table precedes the criterion line
    for line in table.splitlines():
        m = re.match(r"\s+(\w+)\s+(\S+)\s+(-?[\d.]+(?:e[-+]?\d+)?)\s+(\S+)\s", line)
        if m and m.group(1) in MOMENTS + ["male_teach_share", "female_teach_share", "cfr_effect", "wtp_share"]:
            rows[m.group(1)] = (m.group(3), m.group(4))
    extra = {}
    for key, pat in (("score_gap", r"score-level gap (-?[\d.]+) SD"),
                     ("poverty_gap", r"child-poverty gap ([-+]?[\d.]+)"),
                     ("gap_logQ", r"Δlog Q = (-?[\d.]+)"),
                     ("pooled_9010", r"pooled non-teacher 90/10: GE ([\d.]+)"),
                     ("iters", r"polish: (\d+) iterations")):
        m = re.search(pat, text)
        extra[key] = m.group(1) if m else "—"
    return {"theta": t["theta"], "criterion": t["criterion"], "rows": rows, **extra}


def fmt_row(name, args, r, base):
    th = " | ".join(f"{x:.4f}" for x in r["theta"])
    mom = " | ".join(f"{r['rows'].get(k, ('—', '—'))[0]} ({r['rows'].get(k, ('—', '—'))[1]})" for k in MOMENTS)
    return f"| {name} | `{args}` | {r['criterion']:.2f} | {th} | {mom} | {r['score_gap']} | {r['iters']} |"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", default="julia/spatial_model/calibration/runs/polish-noincome")
    a = ap.parse_args()
    cases = [ln.rstrip("\n").split("\t") for ln in CASES.read_text().splitlines()
             if ln.strip() and not ln.startswith("#")]
    base = read_run(ROOT / a.baseline)
    head = ("| case | arguments | criterion | " + " | ".join(NAMES) + " | " +
            " | ".join(f"{k} (res.)" for k in MOMENTS) + " | score gap | LM its |")
    sep = "|" + "---|" * (head.count("|") - 1)
    lines = [
        "# Table 5 sensitivity panel",
        "",
        "Generated by `julia/spatial_model/calibration/slurm/panel_summary.py` from `julia/spatial_model/calibration/runs/panel/`. "
        "Each case changes one input (`panel_cases.tsv`) and refits ϑ by Levenberg–Marquardt "
        "(`spatial_diagnose.jl --polish`, up to 30 iterations) from the baseline estimate, keeping the "
        "baseline frozen reference. Moments are the model value with its standardized residual; "
        "`gap_income` is validation unless the case activates it. Criteria are comparable only across "
        "cases with the same targets and scales.",
        "",
        head, sep,
    ]
    if base:
        lines.append(fmt_row("**baseline**", "—", base, base))
    missing = []
    for name, args in cases:
        r = read_run(PANEL / name)
        if r is None:
            missing.append(name)
            continue
        lines.append(fmt_row(name, args, r, base))
    if missing:
        lines += ["", "Not finished or failed: " + ", ".join(missing) + "."]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(cases) - len(missing)} of {len(cases)} cases)")


if __name__ == "__main__":
    main()
