# Script to plot results generated by ATT.jl
using JLD, Plots, Distributions, LaTeXStrings
d = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=0.94_A=2.0.jld")
# Extract arrays from dictionary 'd':
H_grid = d["H_grid"]
a_grid = d["a_grid"]
HH_T = d["HH_T"]
H_O = d["H_O"]
a_T_thresh = d["a_T_thresh"]
a_O_thresh = d["a_O_thresh"]
e_T = d["e_T"]
s_T = d["s_T"]
e_O = d["e_O"]
s_O = d["s_O"]
t = d["t"]
E_O = d["E_O"]
E_T = d["E_T"]
mass_O = d["mass_O"]
mass_T = d["mass_T"]
f_1 = d["f_1"]
f_2 = d["f_2"]
τ_e = d["τ_e"]
τ_w = d["τ_w"]
A = d["A"]
β = d["β"]
σ = d["σ"]

pyplot()
# Index for H_T:
iHT = 10
# Plot fraction of teachers at each level of a_O (given by a_grid):
plt1 = plot(a_grid,f_1[:,:],label = ["female" "male"],title = latexstring("\\tau_\\omega = "*string(τ_w[1,1])*", \\tau_e = "*string(τ_e[1,1])*", \\frac{β}{σ} = "*string(round(β/σ,digits=3)))) # \\widetilde{H}^T = "*string(round(H_T[iHT],digits=3))))
savefig(plt1,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/occupational_choice_new_grid_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_beta-to-sigma="*string(round(β/σ,digits=2))*"_A="*string(round(A,digits=2))*".eps")
# Plot H^T against H^T':
plt2 = plot(H_grid,[HH_T[1:length(H_grid)] H_grid],label=[latexstring("\\widetilde{H}^{T'}") latexstring("\\widetilde{H}^{T}")])
savefig(plt2,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/fixed_point_H_T_new_grid_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_beta-to-sigma="*string(round(β/σ,digits=2))*"_A="*string(round(A,digits=2))*".eps")
# Plot measure of teachers and "others":
plt3 = plot(H_grid,sum(mass_T,dims=2),label="Teachers")
plt3 = plot!(H_grid,sum(mass_O,dims=2),label="Other")
savefig(plt3,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/measures_H_T_new_grid_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_beta-to-sigma="*string(round(β/σ,digits=2))*"_A="*string(round(A,digits=2))*".eps")
# Plot occupational threshold for different values of β and σ (and constant τ, A,...)
d0 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=0.88_A=2.0.jld")
a_T_thresh = d0["a_T_thresh"]
a_O_thresh = d0["a_O_thresh"]
β = d0["β"]
σ = d0["σ"]
H_grid = d0["H_grid"]
HH_T = d0["HH_T"]
HH_T_cf = d0["HH_T_cf"]
mass_O = d0["mass_O"]
mass_T = d0["mass_T"]
f_1 = d0["f_1"]
plt4 = plot(a_grid,a_T_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt14 = plot(a_grid,a_O_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt6 = plot(H_grid,HH_T[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'$",legend=:topleft)
plt16 = plot(H_grid,HH_T_cf[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'_{cf}$",legend=:topleft)
plt7 = plot(a_grid,f_1[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a$",ylabel="fraction of teachers",legend=:topright)
betasigma = Vector{Float64}(undef, 6)
fracteach = Vector{Float64}(undef, 6)
betasigma[1]=β/σ
fracteach[1]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))


d1 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=0.94_A=2.0.jld")
a_T_thresh = d1["a_T_thresh"]
a_O_thresh = d1["a_O_thresh"]
β = d1["β"]
σ = d1["σ"]
H_grid = d1["H_grid"]
HH_T = d1["HH_T"]
HH_T_cf = d1["HH_T_cf"]
mass_O = d1["mass_O"]
mass_T = d1["mass_T"]
f_1 = d1["f_1"]
plt4 = plot!(plt4,a_grid,a_T_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt14 = plot!(plt14,a_grid,a_O_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt6 = plot!(plt6,H_grid,HH_T[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'$",legend=:topleft)
plt16 = plot!(plt16,H_grid,HH_T_cf[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'_{cf}$",legend=:topleft)
plt7 = plot!(plt7,a_grid,f_1[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a$",ylabel="fraction of teachers",legend=:topright)
betasigma[2]=β/σ
fracteach[2]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))
# plt5 = scatter(β/σ,sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:])),color=:blue)
d2 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=1.0_A=2.0.jld")
a_T_thresh = d2["a_T_thresh"]
a_O_thresh = d2["a_O_thresh"]
β = d2["β"]
σ = d2["σ"]
H_grid = d2["H_grid"]
HH_T = d2["HH_T"]
HH_T_cf = d2["HH_T_cf"]
mass_O = d2["mass_O"]
mass_T = d2["mass_T"]
f_1 = d2["f_1"]
plt4 = plot!(plt4,a_grid,a_T_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt14 = plot!(plt14,a_grid,a_O_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt6 = plot!(plt6,H_grid,HH_T[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'$",legend=:topleft)
plt16 = plot!(plt16,H_grid,HH_T_cf[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'_{cf}$",legend=:topleft)
plt7 = plot!(plt7,a_grid,f_1[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a$",ylabel=L"fraction of teachers",legend=:topright)
betasigma[3]=β/σ
fracteach[3]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))
# plt5 = scatter!(β/σ,sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:])),color=:blue)
d3 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=1.07_A=2.0.jld")
a_T_thresh = d3["a_T_thresh"]
a_O_thresh = d3["a_O_thresh"]
β = d3["β"]
σ = d3["σ"]
H_grid = d3["H_grid"]
HH_T = d3["HH_T"]
HH_T_cf = d3["HH_T_cf"]
mass_O = d3["mass_O"]
mass_T = d3["mass_T"]
f_1 = d3["f_1"]
plt4 = plot!(plt4,a_grid,a_T_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt14 = plot!(plt14,a_grid,a_O_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt6 = plot!(plt6,H_grid,HH_T[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'$",legend=:topleft)
plt16 = plot!(plt16,H_grid,HH_T_cf[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'_{cf}$",legend=:topleft)
plt7 = plot!(plt7,a_grid,f_1[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a$",ylabel=L"fraction of teachers",legend=:topright)
betasigma[4]=β/σ
fracteach[4]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))
# plt5 = scatter!(β/σ,sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:])),color=:blue)
d5 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=1.15_A=2.0.jld")
a_T_thresh = d5["a_T_thresh"]
a_O_thresh = d5["a_O_thresh"]
β = d5["β"]
σ = d5["σ"]
H_grid = d5["H_grid"]
HH_T = d5["HH_T"]
HH_T_cf = d5["HH_T_cf"]
mass_O = d5["mass_O"]
mass_T = d5["mass_T"]
f_1 = d5["f_1"]
plt4 = plot!(plt4,a_grid,a_T_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt14 = plot!(plt14,a_grid,a_O_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))))
plt6 = plot!(plt6,H_grid,HH_T[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'$",legend=:topleft)
plt16 = plot!(plt16,H_grid,HH_T_cf[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'_{cf}$",legend=:topleft)
plt7 = plot!(plt7,a_grid,f_1[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a$",ylabel=L"fraction of teachers",legend=:topright)
betasigma[5]=β/σ
fracteach[5]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))
# plt5 = scatter!(β/σ,sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:])),color=:blue)

d6 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=1.25_A=2.0.jld")
a_T_thresh = d6["a_T_thresh"]
a_O_thresh = d6["a_O_thresh"]
β = d6["β"]
σ = d6["σ"]
H_grid = d1["H_grid"]
HH_T = d6["HH_T"]
HH_T_cf = d6["HH_T_cf"]
mass_O = d6["mass_O"]
mass_T = d6["mass_T"]
f_1 = d6["f_1"]
plt4 = plot!(plt4,a_grid,a_T_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a^O$",ylabel=L"$\bar{a}^T(a^O)$",legend=:topleft)
plt14 = plot!(plt14,a_grid,a_O_thresh[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a^T$",ylabel=L"$\bar{a}^{-1}(a^T)$",legend=:topleft)
plt6 = plot!(plt6,H_grid,HH_T[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'$",legend=:topleft)
plt16 = plot!(plt16,H_grid,HH_T_cf[1:length(H_grid)],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$\widetilde{H^T}$",ylabel=L"$\widetilde{H^T}'_{cf}$",legend=:topleft)
plt6 = plot!(plt6,H_grid,H_grid,line=[:dot],grid=:none,label=L"$45^\circ$")
plt7 = plot!(plt7,a_grid,f_1[:,1],grid=:none,label=latexstring("\\frac{\\beta}{\\sigma} = "*string(round(β/σ,digits=2))),xlabel=L"$a$",ylabel=L"fraction of teachers",legend=:topright)
betasigma[6]=β/σ
fracteach[6]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

plt5 = plot(betasigma,fracteach,grid=:none,color=:blue,linestyle=:dash,markershape=:circle,markersize=5,markercolor=:red,xlabel=L"$\frac{\beta}{\sigma}$",ylabel="fraction of teachers",legend=false)
τ_e = d6["τ_e"]
τ_w = d6["τ_w"]
A = d6["A"]
savefig(plt4,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/occ_thresh_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
savefig(plt14,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/inv_occ_thresh_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
savefig(plt5,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/frac_teachers_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
savefig(plt6,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/law_of_motion_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
savefig(plt16,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/law_of_motion_cf_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
savefig(plt7,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/frac_teachers_by_a_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
# Plot effect of wedges (τ_w and τ_e) on occupational choice (male vs. female)
d8 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.0 0.0]_beta-to-sigma=1.15_A=2.0.jld")
a_grid = d8["a_grid"]
β = d8["β"]
σ = d8["σ"]
f_1 = d8["f_1"]
f_2 = d8["f_2"]
τ_e = d8["τ_e"]
τ_w = d8["τ_w"]
plt8 = plot(a_grid,sum(f_1[:,:],dims=2)./(sum(f_1[:,:],dims=2)+sum(f_2[:,:],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[1])*", \\tau^w = "*string(τ_w[1])),xlabel=L"$a$",ylabel="fraction of teachers")
plt9 = plot(a_grid,sum(f_1[:,:],dims=2)./(sum(f_1[:,:],dims=2)+sum(f_2[:,:],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[1])*", \\tau^w = "*string(τ_w[1])),xlabel=L"$a$",ylabel="fraction of teachers")
plt10 = plot(a_grid,sum(f_1[:,:],dims=2)./(sum(f_1[:,:],dims=2)+sum(f_2[:,:],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[1])*", \\tau^w = "*string(τ_w[1])),xlabel=L"$a$",ylabel="fraction of teachers")
d9 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.1 0.0]_tauE=[0.0 0.0]_beta-to-sigma=1.15_A=2.0.jld")
β = d9["β"]
σ = d9["σ"]
f_1 = d9["f_1"]
f_2 = d9["f_2"]
τ_e = d9["τ_e"]
τ_w = d9["τ_w"]
plt8 = plot!(plt8,a_grid,sum(f_1[:,1],dims=2)./(sum(f_1[:,1],dims=2)+sum(f_2[:,1],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[1])*", \\tau^w = "*string(τ_w[1])*", female"),xlabel=L"$a$",ylabel="fraction of teachers")
plt8 = plot!(plt8,a_grid,sum(f_1[:,2],dims=2)./(sum(f_1[:,2],dims=2)+sum(f_2[:,2],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[2])*", \\tau^w = "*string(τ_w[2])*", male"),xlabel=L"$a$",ylabel="fraction of teachers")
savefig(plt8,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/frac_teachers_by_a_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
d10 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.0 0.0]_tauE=[0.1 0.0]_beta-to-sigma=1.15_A=2.0.jld")
β = d10["β"]
σ = d10["σ"]
f_1 = d10["f_1"]
f_2 = d10["f_2"]
τ_e = d10["τ_e"]
τ_w = d10["τ_w"]
plt9 = plot!(plt9,a_grid,sum(f_1[:,1],dims=2)./(sum(f_1[:,1],dims=2)+sum(f_2[:,1],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[1])*", \\tau^w = "*string(τ_w[1])*", female"),xlabel=L"$a$",ylabel="fraction of teachers")
plt9 = plot!(plt9,a_grid,sum(f_1[:,2],dims=2)./(sum(f_1[:,2],dims=2)+sum(f_2[:,2],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[2])*", \\tau^w = "*string(τ_w[2])*", male"),xlabel=L"$a$",ylabel="fraction of teachers")
savefig(plt9,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/frac_teachers_by_a_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
d11 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_tauW=[0.1 0.0]_tauE=[0.1 0.0]_beta-to-sigma=1.15_A=2.0.jld")
β = d11["β"]
σ = d11["σ"]
f_1 = d11["f_1"]
f_2 = d11["f_2"]
τ_e = d11["τ_e"]
τ_w = d11["τ_w"]
plt10 = plot!(plt10,a_grid,sum(f_1[:,1],dims=2)./(sum(f_1[:,1],dims=2)+sum(f_2[:,1],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[1])*", \\tau^w = "*string(τ_w[1])*", female"),xlabel=L"$a$",ylabel="fraction of teachers")
plt10 = plot!(plt10,a_grid,sum(f_1[:,2],dims=2)./(sum(f_1[:,2],dims=2)+sum(f_2[:,2],dims=2)),grid=:none,label=latexstring("\\tau^e = "*string(τ_e[2])*", \\tau^w = "*string(τ_w[2])*", male"),xlabel=L"$a$",ylabel="fraction of teachers")
savefig(plt10,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/frac_teachers_by_a_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_A="*string(round(A,digits=2))*".eps")
