# Script to plot class size distributions generated by A_thresh_upd.jl:
using JLD, Plots, Distributions, LaTeXStrings
# Number of plots:
pltnm = 10

alpha = Vector{Float64}(undef,pltnm)
beta = Vector{Float64}(undef,pltnm)
eta = Vector{Float64}(undef,pltnm)
sigma = Vector{Float64}(undef,pltnm)
fracteach = Vector{Float64}(undef,pltnm)

pyplot()
# Plot #1.1:
d1 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.5_β=0.3_η=0.5_σ=0.3.jld")
H_grid = d1["H_grid"]
a_grid = d1["a_grid"]
a_T_thresh = d1["a_T_thresh"]
a_O_thresh = d1["a_O_thresh"]
β = d1["β"]
σ = d1["σ"]
α = d1["α"]
η = d1["η"]
H_grid = d1["H_grid"]
HH_T = d1["HH_T"]
HH_T_cf = d1["HH_T_cf"]
mass_O = d1["mass_O"]
mass_T = d1["mass_T"]
f_1 = d1["f_1"]
N=d1["N"]
EN_agg=d1["EN_agg"]
cvN=d1["cvN"]
plt1 = plot(a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
# plt1 = plot(a_grid,N[:,1,1],grid=:none,label=latexstring("\\% in  T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[1]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))
# Plot #1.2:
d2 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.5_β=0.3_η=0.55_σ=0.3.jld")
H_grid = d2["H_grid"]
a_grid = d2["a_grid"]
a_T_thresh = d2["a_T_thresh"]
a_O_thresh = d2["a_O_thresh"]
β = d2["β"]
σ = d2["σ"]
α = d2["α"]
η = d2["η"]
H_grid = d2["H_grid"]
HH_T = d2["HH_T"]
HH_T_cf = d2["HH_T_cf"]
mass_O = d2["mass_O"]
mass_T = d2["mass_T"]
f_1 = d2["f_1"]
N=d2["N"]
EN_agg=d2["EN_agg"]
cvN=d2["cvN"]
plt1 = plot!(plt1,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[2]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #1.3:
d3 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.5_β=0.3_η=0.6_σ=0.3.jld")
H_grid = d3["H_grid"]
a_grid = d3["a_grid"]
a_T_thresh = d3["a_T_thresh"]
a_O_thresh = d3["a_O_thresh"]
β = d3["β"]
σ = d3["σ"]
α = d3["α"]
η = d3["η"]
H_grid = d3["H_grid"]
HH_T = d3["HH_T"]
HH_T_cf = d3["HH_T_cf"]
mass_O = d3["mass_O"]
mass_T = d3["mass_T"]
f_1 = d3["f_1"]
N=d3["N"]
EN_agg=d3["EN_agg"]
cvN=d3["cvN"]
plt1 = plot!(plt1,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[3]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #1.4:
d4 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.5_β=0.3_η=0.65_σ=0.3.jld")
H_grid = d4["H_grid"]
a_grid = d4["a_grid"]
a_T_thresh = d4["a_T_thresh"]
a_O_thresh = d4["a_O_thresh"]
β = d4["β"]
σ = d4["σ"]
α = d4["α"]
η = d4["η"]
H_grid = d4["H_grid"]
HH_T = d4["HH_T"]
HH_T_cf = d4["HH_T_cf"]
mass_O = d4["mass_O"]
mass_T = d4["mass_T"]
f_1 = d4["f_1"]
N=d4["N"]
EN_agg=d4["EN_agg"]
cvN=d4["cvN"]
plt1 = plot!(plt1,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[4]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #1.5:
d5 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.5_β=0.3_η=0.7_σ=0.3.jld")
H_grid = d5["H_grid"]
a_grid = d5["a_grid"]
a_T_thresh = d5["a_T_thresh"]
a_O_thresh = d5["a_O_thresh"]
β = d5["β"]
σ = d5["σ"]
α = d5["α"]
η = d5["η"]
H_grid = d5["H_grid"]
HH_T = d5["HH_T"]
HH_T_cf = d5["HH_T_cf"]
mass_O = d5["mass_O"]
mass_T = d5["mass_T"]
f_1 = d5["f_1"]
N=d5["N"]
EN_agg=d5["EN_agg"]
cvN=d5["cvN"]
plt1 = plot!(plt1,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[5]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #2.1:
d6 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.5_β=0.3_η=0.5_σ=0.3.jld")
H_grid = d6["H_grid"]
a_grid = d6["a_grid"]
a_T_thresh = d6["a_T_thresh"]
a_O_thresh = d6["a_O_thresh"]
β = d6["β"]
σ = d6["σ"]
α = d6["α"]
η = d6["η"]
H_grid = d6["H_grid"]
HH_T = d6["HH_T"]
HH_T_cf = d6["HH_T_cf"]
mass_O = d6["mass_O"]
mass_T = d6["mass_T"]
f_1 = d6["f_1"]
N=d6["N"]
EN_agg=d6["EN_agg"]
cvN=d6["cvN"]
plt2 = plot(a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[6]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #2.2:
d7 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.55_β=0.3_η=0.5_σ=0.3.jld")
H_grid = d7["H_grid"]
a_grid = d7["a_grid"]
a_T_thresh = d7["a_T_thresh"]
a_O_thresh = d7["a_O_thresh"]
β = d7["β"]
σ = d7["σ"]
α = d7["α"]
η = d7["η"]
H_grid = d7["H_grid"]
HH_T = d7["HH_T"]
HH_T_cf = d7["HH_T_cf"]
mass_O = d7["mass_O"]
mass_T = d7["mass_T"]
f_1 = d7["f_1"]
N=d7["N"]
EN_agg=d7["EN_agg"]
cvN=d7["cvN"]
plt2 = plot!(plt2,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[7]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #2.3:
d8 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.6_β=0.3_η=0.5_σ=0.3.jld")
H_grid = d8["H_grid"]
a_grid = d8["a_grid"]
a_T_thresh = d8["a_T_thresh"]
a_O_thresh = d8["a_O_thresh"]
β = d8["β"]
σ = d8["σ"]
α = d8["α"]
η = d8["η"]
H_grid = d8["H_grid"]
HH_T = d8["HH_T"]
HH_T_cf = d8["HH_T_cf"]
mass_O = d8["mass_O"]
mass_T = d8["mass_T"]
f_1 = d8["f_1"]
N=d8["N"]
EN_agg=d8["EN_agg"]
cvN=d8["cvN"]
plt2 = plot!(plt2,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[8]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #2.4:
d9 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.65_β=0.3_η=0.5_σ=0.3.jld")
H_grid = d9["H_grid"]
a_grid = d9["a_grid"]
a_T_thresh = d9["a_T_thresh"]
a_O_thresh = d9["a_O_thresh"]
β = d9["β"]
σ = d9["σ"]
α = d9["α"]
η = d9["η"]
H_grid = d9["H_grid"]
HH_T = d9["HH_T"]
HH_T_cf = d9["HH_T_cf"]
mass_O = d9["mass_O"]
mass_T = d9["mass_T"]
f_1 = d9["f_1"]
N=d9["N"]
EN_agg=d9["EN_agg"]
cvN=d9["cvN"]
plt2 = plot!(plt2,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[9]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Plot #2.5:
d10 = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/results_2_groups_τW=[0.1 0.0]_τE=[0.0 0.0]_A=10.0_α=0.7_β=0.3_η=0.5_σ=0.3.jld")
H_grid = d10["H_grid"]
a_grid = d10["a_grid"]
a_T_thresh = d10["a_T_thresh"]
a_O_thresh = d10["a_O_thresh"]
β = d10["β"]
σ = d10["σ"]
α = d10["α"]
η = d10["η"]
H_grid = d10["H_grid"]
HH_T = d10["HH_T"]
HH_T_cf = d10["HH_T_cf"]
mass_O = d10["mass_O"]
mass_T = d10["mass_T"]
f_1 = d10["f_1"]
N=d10["N"]
EN_agg=d10["EN_agg"]
cvN=d10["cvN"]
plt2 = plot!(plt2,a_grid,N[:,1,1],grid=:none,label=latexstring("\\alpha = "*string(round(α,digits=2))*", \\beta = "*string(round(β,digits=2))*", \\eta = "*string(round(η,digits=2))*", \\sigma = "*string(round(σ,digits=2))*", E(N) = "*string(round(EN_agg,digits=2))*", c.v. = "*string(round(cvN,digits=2))*", \\% in T = "*string(round((gm./(sum(gm))*mass_T)[1],digits=2))))
fracteach[10]=sum(mass_T[:])/(sum(mass_T[:])+sum(mass_O[:]))

# Save plots:
savefig(plt1,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/N_α="*string(round(α,digits=2))*"_β="*string(round(β,digits=2))*"_η="*string(round(η,digits=2))*"_σ="*string(round(σ,digits=2))*".eps")
savefig(plt2,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results_new/N_α="*string(round(α,digits=2))*"_β="*string(round(β,digits=2))*"_η="*string(round(η,digits=2))*"_σ="*string(round(σ,digits=2))*".eps")
