# Script to plot results generated by ATT.jl
using JLD, Plots, Distributions, LaTeXStrings
d = load("/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/results/results_2_groups_tauW=[0.0 0.0]_tauE=[0.1 0.0]_beta-to-sigma=1.2_A=1.0.jld")
# Extract arrays from dictionary 'd':
H_grid = d["H_grid"]
HH_T = d["HH_T"]
H_O = d["H_O"]
λ = d["λ"]
a_T_thresh = d["a_T_thresh"]
a_O_thresh = d["a_O_thresh"]
e_T = d["e_T"]
s_T = d["s_T"]
e_O = d["e_O"]
s_O = d["s_O"]
t = d["t"]
E_O = d["E_O"]
E_T = d["E_T"]
mass_O = d["mass_O"]
mass_T = d["mass_T"]
f_1 = d["f_1"]
f_2 = d["f_2"]
τ_e = d["τ_e"]
τ_w = d["τ_w"]
A = d["A"]

pyplot()
# Index for H_T:
iHT = 10
plt1 = plot(a_grid,f_1[:,iHT,:],label = ["female" "male"],title = latexstring("\\tau_\\omega = "*string(τ_w[1,1])*", \\tau_e = "*string(τ_e[1,1])*", \\frac{β}{σ} = "*string(round(β/σ,digits=3)))) # \\widetilde{H}^T = "*string(round(H_T[iHT],digits=3))))
savefig(plt1,"/Users/simeonalder/Dropbox/Work/Research/GitHub/teachers/julia/plots/occupational_choice_tauW_"*string(τ_w[1,1])*"_tauE_"*string(τ_e[1,1])*"_beta-to-sigma="*string(round(β/σ,digits=1))*"_A="*string(round(A,digits=1))*".eps")
